apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-ratesvc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.ratesvc.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-ratesvc
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ratesvc.image.repository }}:{{ .Values.ratesvc.image.tag }}"
        args:
        - /ratesvc
        - -mongo-host
        - {{ template "mongodb.fullname" . }}
        - -mongo-database
        - ratesvc
        imagePullPolicy: {{ .Values.ratesvc.image.pullPolicy }}
        env:
        {{- if .Values.api.auth.signingKey }}
        - name: JWT_KEY
          value: {{ .Values.api.auth.signingKey }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.ratesvc.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /live
            port: {{ .Values.ratesvc.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.ratesvc.service.internalPort }}
        resources:
{{ toYaml .Values.ratesvc.resources | indent 12 }}
