apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-ratesvc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.ratesvc.service.type }}
  ports:
  - port: {{ .Values.ratesvc.service.externalPort }}
    targetPort: {{ .Values.ratesvc.service.internalPort }}
    protocol: TCP
    name: {{ .Values.ratesvc.service.name }}
  selector:
    app: {{ template "fullname" . }}-ratesvc
